### PR TITLE
Fix install from source in Readme

### PR DESCRIPTION
**Pull request by midN**

### CODE REVIEW

**Comment by midN** [comment]
@birdayz Updating readme to get the installation to match the Makefile

**Comment by birdayz** [comment]
thanks!
i wonder, why explicitly enable gomodules?

**Comment by midN** [comment]
@birdayz Is not enabled by default in all Go versions, or maybe just older ones 🤷‍♂️ 

I'm on 1.11.5, notifies me with "Gomodules disabled" during install, so i figured i'll copy enable from Makefile just in-case

**Comment by birdayz** [comment]
Yeah you should get this warning if you're inside gopath. This is the default behavior for Go 1.11. There's no harm in hard-enabling it. Thanks

**Comment by birdayz** [comment]
Plot twist: this actually does not work outside of the repo! I removed the GO111MODULE env var from the Readme.

**Pull request merged**
